<a href="https://colab.research.google.com/github/jobayed80/Machine_Learning_Learning_Course/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Md. Jobayed Hossain Rabbi
# 193-35-2948

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [2]:
# 1. Import numpy as np and print the version number.
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 1.23.5


In [3]:
# 2. Create a 1D array of numbers from 0 to 9.
array_1d = np.arange(10)
print("1D array:", array_1d)

1D array: [0 1 2 3 4 5 6 7 8 9]


In [4]:
# 3. Create a 3×3 numpy array of all True’s.
array_true = np.ones((3, 3), dtype=bool)
print("3x3 array of True's:")
print(array_true)

3x3 array of True's:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
# 4. Extract all odd numbers from arr.
odd_numbers = array_1d[array_1d % 2 != 0]
odd_numbers

array([1, 3, 5, 7, 9])

In [6]:
# 4. Extract all odd numbers from arr.
odd_numbers = array_1d[array_1d % 2 != 0]
print("Odd numbers:", odd_numbers)


Odd numbers: [1 3 5 7 9]


In [7]:
# 5. Replace all odd numbers in arr with -1.
array_1d[array_1d % 2 != 0] = -1
print("Array after replacing odd numbers -1:")
print(array_1d)

Array after replacing odd numbers -1:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
# 6. Replace all odd numbers in arr with -1 without changing arr. (using np.where)
new_array = np.where(array_1d % 2 != 0, -1, array_1d)
print("New array without changing original arr:")
print(new_array)

New array without changing original arr:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [9]:
# 7 Assuming arr is the 1D array created in task 2
array_2d = array_1d.reshape(2, -1)
print("2D array with 2 rows:")
print(array_2d)

2D array with 2 rows:
[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


In [10]:
# Assume 'a' and 'b' are your two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 8. Stack arrays a and b vertically.
stacked_vertically = np.vstack((a, b))
print("Arrays 'a' and 'b' stacked vertically:\n", stacked_vertically)


Arrays 'a' and 'b' stacked vertically:
 [[1 2 3]
 [4 5 6]]


In [11]:
# 9. Stack the arrays a and b horizontally.
stacked_horizontally = np.hstack((a, b))
print("Arrays 'a' and 'b' stacked horizontally:\n", stacked_horizontally)


Arrays 'a' and 'b' stacked horizontally:
 [1 2 3 4 5 6]


In [12]:
# 10. Create the following pattern without hardcoding, using only numpy functions.
# Pattern: [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
pattern = np.tile(np.repeat(a, 3), 3)
print("Pattern without hardcoding:\n", pattern)

Pattern without hardcoding:
 [1 1 1 2 2 2 3 3 3 1 1 1 2 2 2 3 3 3 1 1 1 2 2 2 3 3 3]


In [13]:
# Assume 'a' and 'b' are your two arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

# 11. Get the common items between a and b.
common_items = np.intersect1d(a, b)
print("Common items between 'a' and 'b':", common_items)

Common items between 'a' and 'b': [3 4 5]


In [14]:
# 12. From array a remove all items present in array b.
a_without_b = np.setdiff1d(a, b)
print("Array 'a' after removing items present in 'b':", a_without_b)

Array 'a' after removing items present in 'b': [1 2]


In [15]:
# 13. Get the positions where elements of a and b match.
matching_positions = np.where(np.isin(a, b))[0]
print("Positions where elements of 'a' and 'b' match:", matching_positions)

Positions where elements of 'a' and 'b' match: [2 3 4]


In [16]:
# 14. Get all items between 5 and 10 from a.
items_between_5_and_10 = a[(a >= 5) & (a <= 10)]
print("Items between 5 and 10 from 'a':", items_between_5_and_10)

Items between 5 and 10 from 'a': [5]


In [17]:
# Assume 'arr' is a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 15. Swap columns 1 and 2 in the array arr.
arr[:, [1, 2]] = arr[:, [2, 1]]
print("Array 'arr' after swapping columns 1 and 2:\n", arr)

Array 'arr' after swapping columns 1 and 2:
 [[1 3 2]
 [4 6 5]
 [7 9 8]]


In [18]:
# 16. Swap rows 1 and 2 in the array arr.
arr[[0, 1], :] = arr[[1, 0], :]
print("Array 'arr' after swapping rows 1 and 2:\n", arr)

Array 'arr' after swapping rows 1 and 2:
 [[4 6 5]
 [1 3 2]
 [7 9 8]]


In [19]:
# 17. Reverse the rows of a 2D array arr.
arr_reversed_rows = np.flipud(arr)
print("Array 'arr' after reversing the rows:\n", arr_reversed_rows)

Array 'arr' after reversing the rows:
 [[7 9 8]
 [1 3 2]
 [4 6 5]]


In [20]:
# 18. Reverse the columns of a 2D array arr.
arr_reversed_columns = np.fliplr(arr)
print("Array 'arr' after reversing the columns:\n", arr_reversed_columns)

Array 'arr' after reversing the columns:
 [[5 6 4]
 [2 3 1]
 [8 9 7]]


In [21]:
# 19. Create a 2D array of shape 5x3 with random decimal numbers between 5 and 10.
rand_arr = np.random.uniform(5, 10, size=(5, 3))
print("Random 2D array of shape 5x3:\n", rand_arr)

Random 2D array of shape 5x3:
 [[8.67498717 9.53021788 8.93706066]
 [7.4044856  5.24741812 7.35442405]
 [6.3941547  9.64104732 9.22543914]
 [6.22231213 7.9437174  6.97833388]
 [5.66440803 8.48378022 6.096147  ]]


In [22]:
# 20. Print or show only 3 decimal places of the numpy array rand_arr.
np.set_printoptions(precision=3)
print("Random array with 3 decimal places:\n", rand_arr)

Random array with 3 decimal places:
 [[8.675 9.53  8.937]
 [7.404 5.247 7.354]
 [6.394 9.641 9.225]
 [6.222 7.944 6.978]
 [5.664 8.484 6.096]]


In [23]:
# Assume rand_arr and a are your arrays
rand_arr = np.random.uniform(5, 10, size=(5, 3))
a = np.array([1, 2, 3, 4, 5, 6])

# 21. Pretty print rand_arr by suppressing the scientific notation.
np.set_printoptions(suppress=True)
print("Pretty printed rand_arr without scientific notation:\n", rand_arr)


Pretty printed rand_arr without scientific notation:
 [[6.941 9.128 8.568]
 [6.742 6.678 6.157]
 [8.795 5.794 7.232]
 [8.502 8.284 8.076]
 [7.558 9.331 5.236]]


In [24]:
# 22. Limit the number of items printed in numpy array a to a maximum of 6 elements.
np.set_printoptions(threshold=6)
print("Array 'a' with a maximum of 6 elements printed:\n", a)

Array 'a' with a maximum of 6 elements printed:
 [1 2 3 4 5 6]


In [25]:
# 23. Print the full numpy array a without truncating.
# Assuming 'a' is your array
np.set_printoptions(threshold=np.inf)
print("Array 'a' without truncation:\n", a)

Array 'a' without truncation:
 [1 2 3 4 5 6]


In [26]:
# 24. Import the iris dataset keeping the text intact.
iris = load_iris()
iris_data = iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [27]:
# 25. Extract the text column species from the 1D iris imported in the previous question.
iris_species = iris.target_names[iris.target]

In [28]:
# 26. Convert the 1D iris to a 2D array iris_2d by omitting the species text field.
iris_2d = np.column_stack((iris_data, iris_species))
iris_2d

array([['5.1', '3.5', '1.4', '0.2', 'setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'setosa'],
       ['5.1', '3.8', '1.5', '0.3', 'setosa'],
       ['5.4', '3.4', '1.7', '0.2', 'setosa'],
       ['5.1'

In [29]:
# 27. Find the mean, median, standard deviation of iris's sepallength (1st column).

sepallength_mean = np.mean(iris_2d[:, 0])
sepallength_median = np.median(iris_2d[:, 0])
sepallength_std = np.std(iris_2d[:, 0])

print("Mean SepalLength:", sepallength_mean)
print("Median SepalLength:", sepallength_median)
print("Standard Deviation SepalLength:", sepallength_std)

UFuncTypeError: ignored

In [ ]:
# 28. Create a normalized form of iris's sepallength.
sepallength_normalized = (iris_2d[:, 0] - np.min(iris_2d[:, 0])) / (np.max(iris_2d[:, 0]) - np.min(iris_2d[:, 0]))


In [ ]:
# Load Iris dataset
iris = load_iris()
sepal_length = iris.data[:, 0]  # Sepal length is in the first column


In [ ]:
# 30. Insert np.nan values at 20 random positions in iris_2d dataset.
np.random.seed(42)
rand_rows = np.random.choice(iris_2d.shape[0], 20, replace=False)
rand_cols = np.random.choice(iris_2d.shape[1], 20, replace=False)
iris_2d[rand_rows, rand_cols] = np.nan

In [ ]:
# 31. Find the number and position of missing values in iris_2d's sepallength.
missing_values_count = np.isnan(iris_2d[:, 0]).sum()
missing_values_positions = np.argwhere(np.isnan(iris_2d[:, 0]))
print("Number of missing values in SepalLength:", missing_values_count)
print("Positions of missing values in SepalLength:", missing_values_positions)


In [ ]:
# 32. Filter the rows of iris_2d that have petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0.
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]


In [ ]:
# 33. Select the rows of iris_2d that do not have any nan value.
non_nan_rows = iris_2d[~np.isnan(iris_2d).any(axis=1)]


In [ ]:
# 34. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d.
correlation = np.corrcoef(iris_2d[:, 0].astype(float), iris_2d[:, 2].astype(float))[0, 1]
print("Correlation between SepalLength and PetalLength:", correlation)

In [ ]:
# 35. Find out if iris_2d has any missing values.
has_missing_values = np.isnan(iris_2d).any()
print("Does iris_2d have any missing values?", has_missing_values)

In [ ]:
# 36. Replace all occurrences of nan with 0 in the numpy array.
iris_2d[np.isnan(iris_2d)] = 0

In [30]:
# 37. Find the unique values and the count of unique values in iris's species.
unique_species, counts = np.unique(iris_species, return_counts=True)
unique_species
counts

array([50, 50, 50])